### ISSUE TITLE
Milestone v0.1.1 Goals

### ISSUE THREAD

**Issue by VaibhavPage** [ocibuilder/ocibuilder#97]
- [x] Implement a unified client for docker and buildah #58 
- [x] Support multiple build contexts #27 
- [x] Implement build spec initializer #84 #85 
- [x] Fix bugs #78 #82
