### ISSUE TITLE
Milestone v0.1.2 Goals

### ISSUE THREAD

**Issue by VaibhavPage** [ocibuilder/ocibuilder#98]
- [ ] Implement Operator #30 #96 
- [x] Documentation #93 
- [ ] Cache flag for ocibuilder #83 
- [x] Support for image labelling #101 
- [ ] ~~Image Diff analysis and implementation #12~~
- [x] Housekeeping #79 
- [x] Remote Overlays #106 
- [x] define grafeas API #91
